### ISSUE TITLE
libcrypto bootstrap

### ISSUE THREAD

**Issue by hzhou0** [chrysalis-blc/whitepaper#1]
When this epic is complete, the multi-platform crypto library will be ready to receive code contributions. 

- [ ]  The library will have a well-defined interface with documentation
- [ ]  The library will have a CI and CD pipeline
- [ ]  The library will have a defined project structure with folders for each platform target
